/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exam;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Asyst
 */
public class FormPembelian extends javax.swing.JFrame {

    /**
     * Creates new form FormPembelian
     */
    public FormPembelian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelForm = new javax.swing.JPanel();
        labelPurchase_ID = new javax.swing.JLabel();
        txtPurchase_ID = new javax.swing.JTextField();
        txtPurchasing_Date = new javax.swing.JTextField();
        labelPurchasing_Date = new javax.swing.JLabel();
        txtVendor_ID = new javax.swing.JTextField();
        labelVendor_ID = new javax.swing.JLabel();
        labeVendor_ReffNo = new javax.swing.JLabel();
        txtVendor_ReffNo = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        txtViewVendorName = new javax.swing.JTextField();
        panelPurchaseDetail = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        labelPurchaseDetail = new javax.swing.JLabel();
        txtProduct_ID1 = new javax.swing.JTextField();
        labelProduct_ID2 = new javax.swing.JLabel();
        txtProduct_ID2 = new javax.swing.JTextField();
        labelProduct_ID3 = new javax.swing.JLabel();
        txtProduct_ID3 = new javax.swing.JTextField();
        labelProduct_ID1 = new javax.swing.JLabel();
        labelProduct_Name1 = new javax.swing.JLabel();
        txtProduct_Name1 = new javax.swing.JTextField();
        labelQty1 = new javax.swing.JLabel();
        txtQty1 = new javax.swing.JTextField();
        txtSubTotal1 = new javax.swing.JTextField();
        labelSubTotal1 = new javax.swing.JLabel();
        txtProduc_tName2 = new javax.swing.JTextField();
        labelProduct_Name2 = new javax.swing.JLabel();
        txtProduct_Name3 = new javax.swing.JTextField();
        labelProduct_Name3 = new javax.swing.JLabel();
        txtQty2 = new javax.swing.JTextField();
        labelQty2 = new javax.swing.JLabel();
        txtQty3 = new javax.swing.JTextField();
        labelQty3 = new javax.swing.JLabel();
        labelPrice1 = new javax.swing.JLabel();
        txtPrice1 = new javax.swing.JTextField();
        labelPrice2 = new javax.swing.JLabel();
        txtPrice2 = new javax.swing.JTextField();
        labelPrice3 = new javax.swing.JLabel();
        txtPrice3 = new javax.swing.JTextField();
        labelSubTotal2 = new javax.swing.JLabel();
        txtSubTotal2 = new javax.swing.JTextField();
        txtSubTotal3 = new javax.swing.JTextField();
        labelSubTotal3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtGrandTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelForm.setBackground(new java.awt.Color(145, 207, 84));

        labelPurchase_ID.setText("Purchase ID                 :");

        txtPurchase_ID.setBackground(new java.awt.Color(237, 213, 39));
        txtPurchase_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPurchase_IDActionPerformed(evt);
            }
        });

        txtPurchasing_Date.setBackground(new java.awt.Color(237, 213, 39));
        txtPurchasing_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPurchasing_DateActionPerformed(evt);
            }
        });

        labelPurchasing_Date.setText("Tanggal                        :");

        txtVendor_ID.setBackground(new java.awt.Color(237, 213, 39));
        txtVendor_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendor_IDActionPerformed(evt);
            }
        });

        labelVendor_ID.setText("Kode Vendor               :");

        labeVendor_ReffNo.setText("Vendor ReffNo            :");

        txtVendor_ReffNo.setBackground(new java.awt.Color(237, 213, 39));
        txtVendor_ReffNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendor_ReffNoActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        txtViewVendorName.setEditable(false);
        txtViewVendorName.setBackground(new java.awt.Color(237, 213, 39));
        txtViewVendorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewVendorNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelFormLayout.createSequentialGroup()
                                .addComponent(labelVendor_ID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVendor_ID))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormLayout.createSequentialGroup()
                                .addComponent(labeVendor_ReffNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtVendor_ReffNo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62)
                        .addComponent(btnView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtViewVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addComponent(labelPurchase_ID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPurchase_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addComponent(labelPurchasing_Date)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPurchasing_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPurchase_ID)
                    .addComponent(txtPurchase_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPurchasing_Date)
                    .addComponent(txtPurchasing_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVendor_ID)
                    .addComponent(txtVendor_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView)
                    .addComponent(txtViewVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeVendor_ReffNo)
                    .addComponent(txtVendor_ReffNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        labelPurchaseDetail.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelPurchaseDetail.setText("Purchase Detail");

        txtProduct_ID1.setBackground(new java.awt.Color(237, 213, 39));
        txtProduct_ID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProduct_ID1ActionPerformed(evt);
            }
        });

        labelProduct_ID2.setText("Product ID 2");

        txtProduct_ID2.setBackground(new java.awt.Color(237, 213, 39));
        txtProduct_ID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProduct_ID2ActionPerformed(evt);
            }
        });

        labelProduct_ID3.setText("Product ID 3");

        txtProduct_ID3.setBackground(new java.awt.Color(237, 213, 39));
        txtProduct_ID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProduct_ID3ActionPerformed(evt);
            }
        });

        labelProduct_ID1.setText("Product ID 1");

        labelProduct_Name1.setText("Nama Product 1");

        txtProduct_Name1.setBackground(new java.awt.Color(237, 213, 39));
        txtProduct_Name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProduct_Name1ActionPerformed(evt);
            }
        });

        labelQty1.setText("Quantity 1");

        txtQty1.setBackground(new java.awt.Color(237, 213, 39));
        txtQty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQty1ActionPerformed(evt);
            }
        });

        txtSubTotal1.setBackground(new java.awt.Color(237, 213, 39));
        txtSubTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotal1ActionPerformed(evt);
            }
        });

        labelSubTotal1.setText("Sub Total 1");

        txtProduc_tName2.setBackground(new java.awt.Color(237, 213, 39));
        txtProduc_tName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProduc_tName2ActionPerformed(evt);
            }
        });

        labelProduct_Name2.setText("Nama Product 2");

        txtProduct_Name3.setBackground(new java.awt.Color(237, 213, 39));
        txtProduct_Name3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProduct_Name3ActionPerformed(evt);
            }
        });

        labelProduct_Name3.setText("Nama Product 3");

        txtQty2.setBackground(new java.awt.Color(237, 213, 39));
        txtQty2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQty2ActionPerformed(evt);
            }
        });

        labelQty2.setText("Quantity 2");

        txtQty3.setBackground(new java.awt.Color(237, 213, 39));
        txtQty3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQty3ActionPerformed(evt);
            }
        });

        labelQty3.setText("Quantity 3");

        labelPrice1.setText("Price 1");

        txtPrice1.setBackground(new java.awt.Color(237, 213, 39));
        txtPrice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrice1ActionPerformed(evt);
            }
        });

        labelPrice2.setText("Price 2");

        txtPrice2.setBackground(new java.awt.Color(237, 213, 39));
        txtPrice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrice2ActionPerformed(evt);
            }
        });

        labelPrice3.setText("Price 3");

        txtPrice3.setBackground(new java.awt.Color(237, 213, 39));
        txtPrice3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrice3ActionPerformed(evt);
            }
        });

        labelSubTotal2.setText("Sub Total 2");

        txtSubTotal2.setBackground(new java.awt.Color(237, 213, 39));
        txtSubTotal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotal2ActionPerformed(evt);
            }
        });

        txtSubTotal3.setBackground(new java.awt.Color(237, 213, 39));
        txtSubTotal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotal3ActionPerformed(evt);
            }
        });

        labelSubTotal3.setText("Sub Total 3");

        javax.swing.GroupLayout panelPurchaseDetailLayout = new javax.swing.GroupLayout(panelPurchaseDetail);
        panelPurchaseDetail.setLayout(panelPurchaseDetailLayout);
        panelPurchaseDetailLayout.setHorizontalGroup(
            panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPurchaseDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPurchaseDetailLayout.createSequentialGroup()
                        .addComponent(labelPurchaseDetail)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelPurchaseDetailLayout.createSequentialGroup()
                        .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPurchaseDetailLayout.createSequentialGroup()
                                .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtProduct_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelProduct_ID1)
                                    .addComponent(txtProduct_ID2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProduct_ID3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelProduct_ID2))
                                .addGap(71, 71, 71)
                                .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelProduct_Name3)
                                    .addComponent(txtProduct_Name3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelProduct_Name1)
                                    .addComponent(txtProduct_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelProduct_Name2)
                                    .addComponent(txtProduc_tName2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelProduct_ID3))
                        .addGap(18, 18, 18)
                        .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelPurchaseDetailLayout.createSequentialGroup()
                                .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelQty1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtQty1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelPurchaseDetailLayout.createSequentialGroup()
                                .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelQty2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtQty2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrice2)))
                            .addGroup(panelPurchaseDetailLayout.createSequentialGroup()
                                .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelQty3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtQty3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrice3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSubTotal1)
                            .addComponent(txtSubTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSubTotal3)
                            .addComponent(txtSubTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSubTotal2)
                            .addComponent(txtSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSimpan))
                        .addGap(27, 27, 27))))
        );
        panelPurchaseDetailLayout.setVerticalGroup(
            panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPurchaseDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPurchaseDetail)
                .addGap(34, 34, 34)
                .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPurchaseDetailLayout.createSequentialGroup()
                        .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelProduct_Name1)
                            .addComponent(labelProduct_ID1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProduct_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProduct_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelProduct_ID2)
                            .addComponent(labelProduct_Name2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProduct_ID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProduc_tName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPurchaseDetailLayout.createSequentialGroup()
                                .addComponent(labelProduct_ID3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProduct_ID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPurchaseDetailLayout.createSequentialGroup()
                                .addComponent(labelProduct_Name3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProduct_Name3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPurchaseDetailLayout.createSequentialGroup()
                                .addComponent(labelQty3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQty3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPurchaseDetailLayout.createSequentialGroup()
                                .addComponent(labelPrice3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPurchaseDetailLayout.createSequentialGroup()
                                .addComponent(labelSubTotal3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSubTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelPurchaseDetailLayout.createSequentialGroup()
                        .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelPurchaseDetailLayout.createSequentialGroup()
                                .addComponent(labelQty2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPurchaseDetailLayout.createSequentialGroup()
                                .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelPurchaseDetailLayout.createSequentialGroup()
                                        .addComponent(labelPrice1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelPurchaseDetailLayout.createSequentialGroup()
                                        .addComponent(labelQty1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtQty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelPurchaseDetailLayout.createSequentialGroup()
                                        .addComponent(labelSubTotal1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSubTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addGroup(panelPurchaseDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelPurchaseDetailLayout.createSequentialGroup()
                                        .addComponent(labelPrice2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelPurchaseDetailLayout.createSequentialGroup()
                                        .addComponent(labelSubTotal2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnSimpan))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKeluar)))
                .addGap(74, 74, 74))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Pembelian");

        txtGrandTotal.setEditable(false);
        txtGrandTotal.setBackground(new java.awt.Color(231, 228, 148));
        txtGrandTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGrandTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGrandTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrandTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelPurchaseDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(panelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPurchaseDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPurchase_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPurchase_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPurchase_IDActionPerformed

    private void txtPurchasing_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPurchasing_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPurchasing_DateActionPerformed

    private void txtVendor_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendor_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendor_IDActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            Statement statement = KoneksiDB.getKoneksi().createStatement();

            int purchaseId = Integer.valueOf(txtPurchase_ID.getText());
            int vendorId = Integer.valueOf(txtVendor_ID.getText());
            String vendorReffNo = txtVendor_ReffNo.getText();
            SimpleDateFormat Originalformat = new SimpleDateFormat("dd-MM-yyyy");
            SimpleDateFormat finalFormat = new SimpleDateFormat("yyyy-MM-dd");
            String purchaseDateStr = txtPurchasing_Date.getText();
            Date date = Originalformat.parse(purchaseDateStr);
            String purchaseDate = finalFormat.format(date);

            //Insert Table Purchase
            String queryPurchase = "insert into purchase values ("
                    + purchaseId + ","
                    + "'" + purchaseDate + "',"
                    + vendorId + ","
                    + "'" + vendorReffNo + "')";
            statement.executeUpdate(queryPurchase);

            String queryPurchaseDetail = "insert into purchase_detail values";
            List<Map<String, Object>> listProduct = new ArrayList();

            String infoStock = "Informasi Stock \n\n";

            if(!txtProduct_ID1.getText().equals("")){
                //select before
                ResultSet selectBefore = statement.executeQuery(
                        "select Stock from product "
                                + "where Product_ID="+txtProduct_ID1.getText());

                while (selectBefore.next()){
                    infoStock = infoStock.concat("Product ID : "
                            +txtProduct_ID1.getText()
                            +"\nStock Sebelum : "+ selectBefore.getString("Stock")
                            +"\n");
                }

                String queryProduct = "update product "
                        + "set Stock = `Stock`+"+txtQty1.getText()
                        + " where Product_ID="+txtProduct_ID1.getText()
                        +";";
                statement.executeUpdate(queryProduct);

                //select after
                ResultSet selectAfter = statement.executeQuery(
                        "select Stock from product "
                                + "where Product_ID="+txtProduct_ID1.getText());

                while (selectAfter.next()){
                    infoStock = infoStock.concat("Stock Sekarang : "
                            + selectAfter.getString("Stock")
                            +"\n\n");
                }

                Map<String, Object> product = new HashMap();
                product.put("productID", txtProduct_ID1.getText());
                product.put("qty", txtQty1.getText());
                product.put("price", txtPrice1.getText());
                product.put("subtotal", txtSubTotal1.getText());
                listProduct.add(product);
            }
            if(!txtProduct_ID2.getText().equals("")){
                //select before
                ResultSet selectBefore = statement.executeQuery(
                        "select Stock from product "
                                + "where Product_ID="+txtProduct_ID2.getText());

                while (selectBefore.next()){
                    infoStock = infoStock.concat("Product ID : "
                            +txtProduct_ID2.getText()
                            +"\nStock Sebelum : "+ selectBefore.getString("Stock")
                            +"\n");
                }

                String queryProduct = "update product "
                        + "set Stock = `Stock`+"+txtQty2.getText()
                        + " where Product_ID="+txtProduct_ID2.getText()
                        +";";
                statement.executeUpdate(queryProduct);

                //select after
                ResultSet selectAfter = statement.executeQuery(
                        "select Stock from product "
                                + "where Product_ID="+txtProduct_ID2.getText());

                while (selectAfter.next()){
                    infoStock = infoStock.concat("Stock Sekarang : "
                            + selectAfter.getString("Stock")
                            +"\n\n");
                }

                Map<String, Object> product = new HashMap();
                product.put("productID", txtProduct_ID2.getText());
                product.put("qty", txtQty2.getText());
                product.put("price", txtPrice2.getText());
                product.put("subtotal", txtSubTotal2.getText());
                listProduct.add(product);
            }
            if(!txtProduct_ID3.getText().equals("")){
                //select before
                ResultSet selectBefore = statement.executeQuery(
                        "select Stock from product "
                                + "where Product_ID="+txtProduct_ID3.getText());

                while (selectBefore.next()){
                    infoStock = infoStock.concat("Product ID : "
                            +txtProduct_ID3.getText()
                            +"\nStock Sebelum : "+ selectBefore.getString("Stock")
                            +"\n\n");
                }

                String queryProduct = "update product "
                        + "set Stock = `Stock`+"+txtQty3.getText()
                        + " where Product_ID="+txtProduct_ID3.getText()
                        +";";
                statement.executeUpdate(queryProduct);

                //select after
                ResultSet selectAfter = statement.executeQuery(
                        "select Stock from product "
                                + "where Product_ID="+txtProduct_ID3.getText());

                while (selectAfter.next()){
                    infoStock = infoStock.concat("Stock Sekarang : "
                            + selectAfter.getString("Stock")
                            +"\n");
                }

                Map<String, Object> product = new HashMap();
                product.put("productID", txtProduct_ID3.getText());
                product.put("qty", txtQty3.getText());
                product.put("price", txtPrice3.getText());
                product.put("subtotal", txtSubTotal3.getText());
                listProduct.add(product);
            }

            int grandTotal = 0;
            for (Map<String, Object> product : listProduct){
                queryPurchaseDetail = queryPurchaseDetail.concat(
                        "("+purchaseId+","
                                + product.get("productID")+","
                                + product.get("qty")+","
                                + product.get("price")+")"
                                + ",");

                String subtotal = (String) product.get("subtotal");
                grandTotal += Integer.valueOf(subtotal);
            }
            txtGrandTotal.setText(String.valueOf(grandTotal));
            queryPurchaseDetail = queryPurchaseDetail.substring(0, queryPurchaseDetail.length() - 1);
            statement.executeUpdate(queryPurchaseDetail);

            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
            JOptionPane.showMessageDialog(null, infoStock);

        } catch (SQLException ex) {
            Logger.getLogger(FormPembelian.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(FormPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtVendor_ReffNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendor_ReffNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendor_ReffNoActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        try {
            // TODO add your handling code here:
            Statement statement = KoneksiDB.getKoneksi().createStatement();
            String vendorID = txtVendor_ID.getText();
            String query = "select Vendor_Name from vendor "
                    + "where Vendor_ID like '%"+vendorID+"%'";
            
            ResultSet rs = statement.executeQuery(query);
            if (rs.next() == false) { 
                txtViewVendorName.setText("");
                JOptionPane.showMessageDialog(null, "Vendor belum terdaftar!");
            } else { 
                do { 
                    txtViewVendorName.setText(rs.getString("Vendor_Name"));
                } while (rs.next()); 
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(FormPembelian.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void txtViewVendorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewVendorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewVendorNameActionPerformed

    private void txtProduct_ID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProduct_ID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProduct_ID1ActionPerformed

    private void txtProduct_ID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProduct_ID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProduct_ID2ActionPerformed

    private void txtProduct_ID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProduct_ID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProduct_ID3ActionPerformed

    private void txtProduct_Name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProduct_Name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProduct_Name1ActionPerformed

    private void txtQty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQty1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQty1ActionPerformed

    private void txtSubTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotal1ActionPerformed

    private void txtProduc_tName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProduc_tName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProduc_tName2ActionPerformed

    private void txtProduct_Name3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProduct_Name3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProduct_Name3ActionPerformed

    private void txtQty2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQty2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQty2ActionPerformed

    private void txtQty3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQty3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQty3ActionPerformed

    private void txtPrice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrice1ActionPerformed

    private void txtPrice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrice2ActionPerformed

    private void txtPrice3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrice3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrice3ActionPerformed

    private void txtSubTotal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotal2ActionPerformed

    private void txtSubTotal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotal3ActionPerformed

    private void txtGrandTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrandTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrandTotalActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda ingin keluar?");
            switch (confirm){
                case JOptionPane.YES_OPTION:
                System.exit(0);
                break;              
            }
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labeVendor_ReffNo;
    private javax.swing.JLabel labelPrice1;
    private javax.swing.JLabel labelPrice2;
    private javax.swing.JLabel labelPrice3;
    private javax.swing.JLabel labelProduct_ID1;
    private javax.swing.JLabel labelProduct_ID2;
    private javax.swing.JLabel labelProduct_ID3;
    private javax.swing.JLabel labelProduct_Name1;
    private javax.swing.JLabel labelProduct_Name2;
    private javax.swing.JLabel labelProduct_Name3;
    private javax.swing.JLabel labelPurchaseDetail;
    private javax.swing.JLabel labelPurchase_ID;
    private javax.swing.JLabel labelPurchasing_Date;
    private javax.swing.JLabel labelQty1;
    private javax.swing.JLabel labelQty2;
    private javax.swing.JLabel labelQty3;
    private javax.swing.JLabel labelSubTotal1;
    private javax.swing.JLabel labelSubTotal2;
    private javax.swing.JLabel labelSubTotal3;
    private javax.swing.JLabel labelVendor_ID;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelPurchaseDetail;
    private javax.swing.JTextField txtGrandTotal;
    private javax.swing.JTextField txtPrice1;
    private javax.swing.JTextField txtPrice2;
    private javax.swing.JTextField txtPrice3;
    private javax.swing.JTextField txtProduc_tName2;
    private javax.swing.JTextField txtProduct_ID1;
    private javax.swing.JTextField txtProduct_ID2;
    private javax.swing.JTextField txtProduct_ID3;
    private javax.swing.JTextField txtProduct_Name1;
    private javax.swing.JTextField txtProduct_Name3;
    private javax.swing.JTextField txtPurchase_ID;
    private javax.swing.JTextField txtPurchasing_Date;
    private javax.swing.JTextField txtQty1;
    private javax.swing.JTextField txtQty2;
    private javax.swing.JTextField txtQty3;
    private javax.swing.JTextField txtSubTotal1;
    private javax.swing.JTextField txtSubTotal2;
    private javax.swing.JTextField txtSubTotal3;
    private javax.swing.JTextField txtVendor_ID;
    private javax.swing.JTextField txtVendor_ReffNo;
    private javax.swing.JTextField txtViewVendorName;
    // End of variables declaration//GEN-END:variables
}
